apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}


  labels:
    app: anyconverter
    component: ui
spec:
  selector:
    matchLabels:
      app: anyconverter
      component: ui
  replicas: 1
  template:
    metadata:
      name: ui
      namespace: {{ .Release.Namespace }}
      labels:
        app: anyconverter
        component: ui
    spec:
      containers:
        - name: ui
          image: {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          livenessProbe:
            tcpSocket:
              port: {{.Values.ui.port}}
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          resources:
            limits:
              cpu: {{ .Values.ui.resources.limits.cpu }}
              memory: {{ .Values.ui.resources.limits.memory }}
            requests:
              cpu: {{ .Values.ui.resources.requests.cpu }}
              memory: {{ .Values.ui.resources.requests.memory }}
          env:
            - name: API_HOST
              value: "{{ .Values.api.service.name }}.{{ .Release.Namespace }}.svc.cluster.local"
            - name: API_PORT
              value: {{ .Values.api.port | quote}}
          ports:
            - containerPort: {{ .Values.ui.port }}
              name: ui-http
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/resolver.conf
              subPath: resolver.conf
              name: nginx-resolver
      volumes:
        - name: nginx-resolver
          configMap:
            name: nginx-resolver
            items:
              - key: resolver.conf
                path: resolver.conf
