apiVersion: v1
kind: Service
metadata:
  name: anyconverter-ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: anyconverter
    component: ui
  type: ClusterIP
  ports:
    - name: ui-http
      protocol: TCP
      targetPort: {{ .Values.ui.port }}
      port: {{ .Values.ui.port }}
