apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: anyconverter
    component: api
  type: ClusterIP
  ports:
    - name: api-http
      protocol: TCP
      targetPort: {{ .Values.api.port }}
      port: {{ .Values.api.port }}
