name: Docker


on:
  push:
    branches:
      - v2
      - v3

env:
  IMAGE_TAG: ${{ github.ref_name }}
  CACHE_TAG: ${{ github.ref_name }}-buildkit-cache

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - longname: linux/amd64
            shortname: amd64
          - longname: linux/arm64
            shortname: arm64
        image:
          - name: jvanmelckebeke/anyconvert-api
            shortname: anyconvert-api
            context: ./api
          - name: jvanmelckebeke/anyconvert-ui
            shortname: anyconvert-ui
            context: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image.name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.context }}/Dockerfile
          platforms: ${{ matrix.platform.longname }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ matrix.image.name }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=registry,ref=${{ matrix.image.name }}:${{ env.CACHE_TAG }}-${{ matrix.platform.shortname }}
          cache-to: type=registry,ref=${{ matrix.image.name }}:${{ env.CACHE_TAG }}-${{ matrix.platform.shortname }},mode=max
      - name: Export digest
        run: |
          mkdir -p /tmp/digest/${{ matrix.image.shortname }}
          digest="${{ steps.build.outputs.digest }}"
          touch /tmp/digest/${{matrix.image.shortname}}/${digest#sha256:}
      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digest-${{ matrix.image.shortname }}
          path: /tmp/digest/${{matrix.image.shortname}}/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        image:
          - name: jvanmelckebeke/anyconvert-api
            shortname: anyconvert-api
          - name: jvanmelckebeke/anyconvert-ui
            shortname: anyconvert-ui
    steps:
      - name: Download digest
        uses: actions/download-artifact@v3
        with:
          name: digest-${{ matrix.image.shortname }}
          path: /tmp/digest/${{matrix.image.shortname}}/
      - name: debug - ls
        run: |
          ls -la /tmp/digest/${{matrix.image.shortname}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image.name }}
          tags: |
            type=raw,value=latest
            type=raw,value={{branch}}
      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digest/${{matrix.image.shortname}}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ matrix.image.name }}@sha256:%s ' *)          

